# Analysis max_return.csv

In [ ]:
import pandas as pd

In [ ]:
max_return_csv = "results/max_return.csv"

df = pd.read_csv(max_return_csv, sep=";")
df

,model,env,env_args,seed,max_return,test_max_return
0,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"(('benchmark_data', True), ('dynamic_rescaling...",0,2.500000,1.328125
1,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"(('benchmark_data', True), ('dynamic_rescaling...",1,1.992188,1.484375

In [ ]:
agg_df = df.groupby(["model", "env", "env_args"]).agg(
    count = ("seed", "count"),
    max_return_mean = ("max_return", "mean"),
    max_return_std  = ("max_return", "std"),
    test_max_return_mean = ("test_max_return", "mean"),
    test_max_return_std  = ("test_max_return", "std"),
)
agg_df

,,,count,max_return_mean,max_return_std,test_max_return_mean,test_max_return_std
model,env,env_args,,,,,
mappo-gnn_cr0.5,mpe2-simple-tag-v3,"(('benchmark_data', True), ('dynamic_rescaling', True), ('key', 'mpe2-simple-tag-v3'), ('max_cycles', 50), ('num_adversaries', 6), ('num_good', 2), ('num_obstacles', 0), ('observation_range', 0.25), ('pretrained_wrapper', 'FrozenTag'), ('render_mode', 'rgb_array'), ('time_limit', 100), ('visual_comm_range', 0.5))",2,2.246094,0.359078,1.40625,0.110485